const var1='Akshata';
const var2='Pooja';
const var3='Meghana';
const var4='Sonam';
const var5='Akshay';
const var6='Ashwin';
const var7='Chaithra';
const var8='Deekshita';
const var9='Arati';
const var10='Ankita';

console.log("************Upper Case************");
let elem=var1.toUpperCase();
console.log(elem);
elem=var2.toUpperCase();
console.log(elem);
elem=var3.toUpperCase();
console.log(elem);
elem=var4.toUpperCase();
console.log(elem);
elem=var5.toUpperCase();
console.log(elem);
elem=var6.toUpperCase();
console.log(elem);
elem=var7.toUpperCase();
console.log(elem);
elem=var8.toUpperCase();
console.log(elem);
elem=var9.toUpperCase();
console.log(elem);
elem=var10.toUpperCase();

console.log("************Lower Case************");
elem=var1.toLowerCase();
console.log(elem);
elem=var2.toLowerCase();
console.log(elem);
elem=var3.toLowerCase();
console.log(elem);
elem=var4.toLowerCase();
console.log(elem);
elem=var5.toLowerCase();
console.log(elem);
elem=var6.toLowerCase();
console.log(elem);
elem=var7.toLowerCase();
console.log(elem);
elem=var8.toLowerCase();
console.log(elem);
elem=var9.toLowerCase();
console.log(elem);
elem=var10.toLowerCase();
console.log(elem);

console.log("************Character AT ************");
elem=var1.charAt(1);
console.log(elem);
elem=var2.charAt(3);
console.log(elem);
elem=var3.charAt(5);
console.log(elem);
elem=var4.charAt(7);
console.log(elem);
elem=var5.charAt(9);
console.log(elem);
elem=var6.charAt(1);
console.log(elem);
elem=var7.charAt(2);
console.log(elem);
elem=var8.charAt(3);
console.log(elem);
elem=var9.charAt(5);
console.log(elem);
elem=var10.charAt(1);
console.log(elem);


console.log("************Concat ************");
elem=var1.concat('ta');
console.log(elem);
elem=var2.concat('ta');
console.log(elem);
elem=var3.concat('ta');
console.log(elem);
elem=var4.concat('ta');
console.log(elem);
elem=var5.concat('ta');
console.log(elem);
elem=var6.concat('ta');
console.log(elem);
elem=var7.concat('ta');
console.log(elem);
elem=var8.concat('ta');
console.log(elem);
elem=var9.concat('ta');
console.log(elem);
elem=var10.concat('ta');

console.log("************Includes ************");
elem=var1.includes('ta',4);
console.log(elem);
elem=var2.includes('ta',4);
console.log(elem);
elem=var3.includes('ta',4);
console.log(elem);
elem=var4.includes('ta',4);
console.log(elem);
elem=var5.includes('ta',4);
console.log(elem);
elem=var6.includes('ta',4);
console.log(elem);
elem=var7.includes('ta',4);
console.log(elem);
elem=var8.includes('ta',4);
console.log(elem);
elem=var9.includes('ta',4);
console.log(elem);
elem=var10.includes('ta',4);
console.log(elem);

console.log("************ Replace ************");
elem=var1.replace('ta','aa');
console.log(elem);
elem=var2.replace('ja','ju');
console.log(elem);
elem=var3.replace('ana','aa');
console.log(elem);
elem=var4.replace('am','aa');
console.log(elem);
elem=var5.replace('ay','aa');
console.log(elem);
elem=var6.replace('win','wini');
console.log(elem);
elem=var7.replace('shi','shee');
console.log(elem);
elem=var8.replace('ta','aa');
console.log(elem);
elem=var9.replace('ti','aa');
console.log(elem);
elem=var10.replace('ta','aa');
console.log(elem);

console.log("************ Search ************");
elem=var1.search('ta');
console.log(elem);
elem=var2.search('ja');
console.log(elem);
elem=var3.search('ana');
console.log(elem);
elem=var4.search('am');
console.log(elem);
elem=var5.search('ay');
console.log(elem);
elem=var6.search('win');
console.log(elem);
elem=var7.search('shi');
console.log(elem);
elem=var8.search('ta');
console.log(elem);
elem=var9.search('ti');
console.log(elem);
elem=var10.search('ta');
console.log(elem);

console.log("************ trim ************");
elem=var1.trim();
console.log(elem);
elem=var2.trim();
console.log(elem);
elem=var3.trim();
console.log(elem);
elem=var4.trim();
console.log(elem);
elem=var5.trim();
console.log(elem);
elem=var6.trim();
console.log(elem);
elem=var7.trim();
console.log(elem);
elem=var8.trim();
console.log(elem);
elem=var9.trim();
console.log(elem);
elem=var10.trim();
console.log(elem);

console.log("************ substring ************");
elem=var1.substr(1,7);
console.log(elem);
elem=var2.substr(1,7);
console.log(elem);
elem=var3.substr(1,7);
console.log(elem);
elem=var4.substr(1,7);
console.log(elem);
elem=var5.substr(1,7);
console.log(elem);
elem=var6.substr(1,7);
console.log(elem);
elem=var7.substr(1,7);
console.log(elem);
elem=var8.substr(1,7);
console.log(elem);
elem=var9.substr(1,7);
console.log(elem);
elem=var10.substr(1,7);
console.log(elem);

console.log("************ split ************");
elem=var1.split('t');
console.log(elem);
elem=var2.split('o',2);
console.log(elem);
elem=var3.split('g');
console.log(elem);
elem=var4.split('n',2);
console.log(elem);
elem=var5.split('a',2);
console.log(elem);
elem=var6.split('w');
console.log(elem);
elem=var7.split('t',1);
console.log(elem);
elem=var8.split('t');
console.log(elem);
elem=var9.split('n',2);
console.log(elem);
elem=var10.split('a',2);
console.log(elem);



